#!/bin/bash
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
pw-jack Surge\ XT &
../../../bin/soundbank-synth --in 'Midi Through:Midi Through Port-1' &
./syntina-driver --config syntina-driver.conf

