
../../../bin/lsmidiouts: lsmidiouts.o
	gcc -o ../../../bin/lsmidiouts lsmidiouts.o -lasound

lsmidiouts.o: lsmidiouts.c
	gcc -c lsmidiouts.c

rtmidi.o: ../../3rdparty/rtmidi/rtmidi.cpp
	gcc -d__WINDOWS_MM__ -I../..\/rdparty/rtmidi -c ../../3rdparty/rtmidi/rtmidi.cpp

rtmidi_c.obj: ../../3rdparty/rtmidi/rtmidi_c.cpp
	gcc -I../../3rdparty/rtmidi -c ../../3rdparty/rtmidi/rtmidi_c.cpp

clean:
	rm -f lsmidiouts.o
	rm -f rtmidi.o
	rm -f rtmidi_c.o

reallyclean: clean
	rm -f ../../../bin/lsmidiouts

