
CC=gcc

../../bin/average-tempo: average-tempo.o midifile.o
	$(CC) -o../../bin/average-tempo average-tempo.o midifile.o

average-tempo.o: average-tempo.c ../midifile/midifile.h
	$(CC) -I../midifile -c average-tempo.c

midifile.o: ../midifile/midifile.c ../midifile/midifile.h
	$(CC) -I../midifile -c ../midifile/midifile.c

clean:
	rm -f average-tempo.o
	rm -f midifile.o

reallyclean: clean
	rm -f ../../bin/average-tempo

