
CC=gcc

../../bin/verbosify: verbosify.o midimsg.o
	$(CC) -o ../../bin/verbosify verbosify.o midimsg.o

verbosify.o: verbosify.c
	$(CC) -I../midimsg -c verbosify.c

midimsg.o: ../midimsg/midimsg.c
	$(CC) -I../midimsg -c ../midimsg/midimsg.c

clean:
	rm -f verbosify.o
	rm -f midimsg.o

reallyclean: clean
	rm -f ../../bin/verbosify

