
CC=gcc

../../bin/dispmidi: dispmidi.o midimsg.o
	$(CC) -o ../../bin/dispmidi dispmidi.o midimsg.o

dispmidi.o: dispmidi.c
	$(CC) -I../midimsg -c dispmidi.c

midimsg.o: ../midimsg/midimsg.c
	$(CC) -I../midimsg -c ../midimsg/midimsg.c

clean:
	rm -f dispmidi.o
	rm -f midimsg.o

reallyclean: clean
	rm -f ../../bin/dispmidi

