
GTK_HOME=c:\gtk

midibrowser.exe: midibrowser.obj
	cl /nologo /Femidibrowser.exe midibrowser.obj $(GTK_HOME)\lib\gtk-win32-2.0.lib $(GTK_HOME)\lib\gdk-win32-2.0.lib $(GTK_HOME)\lib\glib-2.0.lib $(GTK_HOME)\lib\gobject-2.0.lib

midibrowser.obj: midibrowser.c
	cl /nologo /c midibrowser.c /I$(GTK_HOME)\include\gtk-2.0

clean:
	@if exist midibrowser.obj del midibrowser.obj

reallyclean: clean
	@if exist midibrowser.exe del midibrowser.exe

