
default:
	test -d target || mkdir target
	cd target && qmake ..
	cd target && make
ifeq ("$(shell uname -s)", "Darwin")
	rm -rf ../../bin/delta.app ../../bin/delta
	cp -r target/delta.app ../../bin
	cp ../midiutil/open-mac-app ../../bin/delta
else
	cp target/delta ../../bin
endif

clean:
	rm -rf target

reallyclean: clean
ifeq ("$(shell uname -s)", "Darwin")
	rm -rf ../../bin/delta.app  ../../bin/delta
else
	rm -f ../../bin/delta
endif

