
default:
	@if not exist target mkdir target
	cd target && qmake ..
	cd target && nmake /nologo
	copy target\release\delta.exe ..\..\bin
	windeployqt ..\..\bin\delta.exe

clean:
	@if exist target rmdir /s /q target

reallyclean: clean
	@if exist ..\..\bin\delta.exe del ..\..\bin\delta.exe

