
../../../bin/lsmidiins: lsmidiins.o
	gcc -o ../../../bin/lsmidiins lsmidiins.o -lasound

lsmidiins.o: lsmidiins.c
	gcc -c lsmidiins.c

rtmidi.o: ../../3rdparty/rtmidi/rtmidi.cpp
	gcc -d__WINDOWS_MM__ -I../..\/rdparty/rtmidi -c ../../3rdparty/rtmidi/rtmidi.cpp

rtmidi_c.obj: ../../3rdparty/rtmidi/rtmidi_c.cpp
	gcc -I../../3rdparty/rtmidi -c ../../3rdparty/rtmidi/rtmidi_c.cpp

clean:
	rm -f lsmidiins.o
	rm -f rtmidi.o
	rm -f rtmidi_c.o

reallyclean: clean
	rm -f ../../../bin/lsmidiins

