
CC=gcc

../../bin/pipe2alsamidi: pipe2alsamidi.o
	$(CC) -o ../../bin/pipe2alsamidi -lasound pipe2alsamidi.o

pipe2alsamidi.o: pipe2alsamidi.c
	$(CC) -c pipe2alsamidi.c

clean:
	rm -f pipe2alsamidi.o

reallyclean: clean
	rm -f ../../bin/pipe2alsamidi

