
..\..\bin\onmessage.exe: onmessage.obj
	cl /nologo /Fe..\..\bin\onmessage.exe onmessage.obj winmm.lib

onmessage.obj: onmessage.c
	cl /nologo /I. /c onmessage.c

clean:
	@if exist onmessage.obj del onmessage.obj

reallyclean: clean
	@if exist ..\..\bin\onmessage.exe del ..\..\bin\onmessage.exe

