
default:
	@if not exist target mkdir target
	cd target && qmake ..
	cd target && nmake /nologo
	copy target\release\qwertymidi.exe ..\..\bin
	windeployqt ..\..\bin\qwertymidi.exe

clean:
	@if exist target rmdir /s /q target

reallyclean: clean
	@if exist ..\..\bin\qwertymidi.exe del ..\..\bin\qwertymidi.exe

