#ifndef IDS_INCLUDED
#define IDS_INCLUDED

enum
{
	SEQER_ID_NEW_WINDOW = wxID_HIGHEST + 1,
	SEQER_ID_SELECT_NONE,
	SEQER_ID_SELECT_TIME_RANGE,
	SEQER_ID_PLAY,
	SEQER_ID_STOP,
	SEQER_ID_RECORD,
	SEQER_ID_SET_PLAYBACK_POSITION,
	SEQER_ID_GO_TO_PLAYBACK_POSITION,
	SEQER_ID_NEXT_MARKER,
	SEQER_ID_PREVIOUS_MARKER,
	SEQER_ID_GO_TO_MARKER,
	SEQER_ID_EXTERNAL_UTILITY,
	SEQER_ID_RECORD_MACRO,
	SEQER_ID_MACROS,
	SEQER_ID_HIGHEST
};

#endif
