
CC=gcc

../../bin/metercaster: metercaster.o midifile.o
	$(CC) -o../../bin/metercaster metercaster.o midifile.o

metercaster.o: metercaster.c ../midifile/midifile.h
	$(CC) -I../midifile -c metercaster.c

midifile.o: ../midifile/midifile.c ../midifile/midifile.h
	$(CC) -I../midifile -c ../midifile/midifile.c

clean:
	rm -f metercaster.o
	rm -f midifile.o

reallyclean: clean
	rm -f ../../bin/metercaster

