
CC=gcc

../../../bin/adispmidi: adispmidi.o
	$(CC) -o ../../../bin/adispmidi adispmidi.o -lasound

adispmidi.o: adispmidi.c
	$(CC) -c adispmidi.c

clean:
	rm -f adispmidi.o

reallyclean: clean
	rm -f ../../../bin/adispmidi

