#ifndef EVENT_TYPE_INCLUDED
#define EVENT_TYPE_INCLUDED

#include <wx/wx.h>
#include <midifile.h>

class EventList;

typedef enum
{
	SEQER_EVENT_TYPE_INVALID = -1,
	SEQER_EVENT_TYPE_NOTE,
	SEQER_EVENT_TYPE_CONTROL_CHANGE,
	SEQER_EVENT_TYPE_PROGRAM_CHANGE,
	SEQER_EVENT_TYPE_AFTERTOUCH,
	SEQER_EVENT_TYPE_PITCH_BEND,
	SEQER_EVENT_TYPE_SYSTEM_EXCLUSIVE,
	SEQER_EVENT_TYPE_TEXT,
	SEQER_EVENT_TYPE_LYRIC,
	SEQER_EVENT_TYPE_MARKER,
	SEQER_EVENT_TYPE_PORT,
	SEQER_EVENT_TYPE_TEMPO,
	SEQER_EVENT_TYPE_TIME_SIGNATURE,
	SEQER_EVENT_TYPE_KEY_SIGNATURE,
	SEQER_EVENT_TYPE_HIGHEST
}
SeqerEventType_t;

wxString SeqerEventType_getName(SeqerEventType_t event_type);
SeqerEventType_t SeqerEvent_getType(MidiFileEvent_t event);

#endif
