
..\..\bin\midimon.exe: midimon.c
	cl /nologo /Fe..\..\bin\midimon.exe midimon.c winmm.lib

clean:
	@if exist midimon.obj del midimon.obj

reallyclean: clean
	@if exist ..\..\bin\midimon.exe del ..\..\bin\midimon.exe

