
..\..\bin\netmidic.exe: netmidic.c
	cl /nologo /Fe..\..\bin\netmidic.exe netmidic.c winmm.lib wsock32.lib

clean:
	@if exist netmidic.obj del netmidic.obj

reallyclean: clean
	@if exist ..\..\bin\netmidic.exe del ..\..\bin\netmidic.exe

