
..\..\bin\joycc.exe: joycc.c
	cl /nologo /Fe..\..\bin\joycc.exe joycc.c winmm.lib

clean:
	@if exist joycc.obj del joycc.obj

reallyclean: clean
	@if exist ..\..\bin\joycc.exe del ..\..\bin\joycc.exe

