
CC=gcc

../../bin/alsamidi2pipe: alsamidi2pipe.o
	$(CC) -o ../../bin/alsamidi2pipe -lasound alsamidi2pipe.o

alsamidi2pipe.o: alsamidi2pipe.c
	$(CC) -c alsamidi2pipe.c

clean:
	rm -f alsamidi2pipe.o

reallyclean: clean
	rm -f ../../bin/alsamidi2pipe

