
CC=gcc

../../bin/net2alsamidi: net2alsamidi.o
	$(CC) -o ../../bin/net2alsamidi net2alsamidi.o -lasound

net2alsamidi.o: net2alsamidi.c
	$(CC) -c net2alsamidi.c

clean:
	rm -f net2alsamidi.o

reallyclean: clean
	rm -f ../../bin/net2alsamidi

